### ISSUE TITLE
The invalid download link？

### ISSUE THREAD

**Issue by Noah-Jrh** [RTC-research-group/LIPSFUS-Event-driven-dataset#1]
I noticed that the link (https://lara.eii.us.es:5555/sharing/lM05D30eS) of the dataset given in github is not working. I tried to download it several times but I always got an error message. Could you please check if the link is valid and functional?

Alternatively, would it be possible for you to use a common network disk, such as Google Drive or Dropbox, to open source the dataset? This way, it would be easier for other researchers to access and use your data for their own studies.

**Comment by alinaresb** [comment]
Dear Noah,
I've just checked it and the link is working. Are you using the password?
[cid:72fe8efa-e27d-43f4-b9de-1c5e532e5aac]
Let me know if you could make it.
Best,
 Alejandro.
________________________________
De: Noah ***@***.***>
Enviado: sábado, 10 de junio de 2023 9:11
Para: RTC-research-group/LIPSFUS-Event-driven-dataset ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [RTC-research-group/LIPSFUS-Event-driven-dataset] The invalid download link？ (Issue #1)


I noticed that the link (https://lara.eii.us.es:5555/sharing/lM05D30eS) of the dataset given in github is not working. I tried to download it several times but I always got an error message. Could you please check if the link is valid and functional?

Alternatively, would it be possible for you to use a common network disk, such as Google Drive or Dropbox, to open source the dataset? This way, it would be easier for other researchers to access and use your data for their own studies.

―

**Comment by Noah-Jrh** [comment]
Now the link is working. Maybe it was a network problem before.  Thank you for your feedback!
